### ISSUE TITLE
NATS Spring Cloud Stream Binder wildcard support

### ISSUE THREAD

**Issue by lucaperico25** [nats-io/spring-nats#11]
It looks like the binder does not support wildcard subjects. A listener binded to _event.*_, consume only message in _event_

application.yml

```
spring:
   cloud:
     stream:
       bindings:
         input:
           destination: "event.*"
           binder: nats

nats:
  spring:
    server: nats://localhost:4222`
```
build.gradle
```    
...
dependencyManagement {
        imports {
            mavenBom "org.springframework.boot:spring-boot-dependencies:2.2.2.RELEASE"
        }
        imports {
            mavenBom "org.springframework.cloud:spring-cloud-dependencies:Hoxton.RELEASE"
        }
    }
...
dependencies {
    api 'io.nats:nats-spring-cloud-stream-binder:0.4.0'
```

During binder initialisation, I see a call (package _org.springframework.cloud.stream.config_) to 
```
public void setDestination(String destination) {
   this.destination = destination;
}
```
where parameter _destination = event_. The wildcard _*_ has been filtered out
